# Generated by Django 5.0.1 on 2024-01-14 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='fecha_prestamo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
